#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

#This is specific to you module, so you need to change it accordingly.
# we read a json stdin {"vars1":true, "var2":"foo", "vars3": 3} and we writ it to .config/state/environment
# Upper case to set environment variable and minor case to read from stdin

# Set MARIADB set environment variables
MARIADB_ROOT_PASSWORD = data.get('MARIADB_ROOT_PASSWORD', 'Nethesis@1234')
MARIADB_DATABASE = data.get('MARIADB_DATABASE', 'solidinvoice')
MARIADB_USER = data.get('MARIADB_USER', 'solidinvoice')
MARIADB_PASSWORD = data.get('MARIADB_PASSWORD', 'solidinvoice@1234')

db_config = {
    'MARIADB_ROOT_PASSWORD': MARIADB_ROOT_PASSWORD,
    'MARIADB_DATABASE': MARIADB_DATABASE,
    'MARIADB_USER': MARIADB_USER,
    'MARIADB_PASSWORD': MARIADB_PASSWORD,
    "MARIADB_AUTO_UPGRADE": "1"
}
agent.write_envfile('database.env', db_config)

# Configure Application Variables


SOLIDINVOICE_ENV = data.get('SOLIDINVOICE_ENV', 'prod')
SOLIDINVOICE_DEBUG = data.get('SOLIDINVOICE_DEBUG', '0')
database_driver = data.get('database_driver', 'pdo_mysql')
database_host = data.get('database_host', 'mariadb-app')
database_port = data.get('database_port', '3306')
database_name = data.get('database_name', 'solidinvoice')
database_user = data.get('database_user', 'solidinvoice')
database_password = data.get('database_password', 'solidinvoice@1234')

app_config = {
    'SOLIDINVOICE_ENV': SOLIDINVOICE_ENV,
    'SOLIDINVOICE_DEBUG': SOLIDINVOICE_DEBUG,
    'database_driver': database_driver,
    'database_host': database_host,
    'database_port': database_port,
    'database_name': database_name,
    'database_user': database_user,
    'database_password': database_password,
    "APP_PORT": "8000"
}
agent.write_envfile('app.env', app_config)

# just before starting systemd unit
#agent.dump_env()
